modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "${github}"
license = "custom"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "LizardOfOz"
description = "${mod_description}"
logoFile = "icon.png"
displayURL="${github}"

[[dependencies.drg_flares]]
modId = "minecraft"
mandatory = true
versionRange = "[${base_mc_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.drg_flares]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"